<?php
return array(
	"ID" => "ID",
	"User" => "User",
	"Module" => "Module",
	"Log" => "Log",
    "System log" => "System log",
	"Created at" => "Created at",
	"Website module" => "Website module",
	"All systems log has been removed" => "All systems log has been removed",
	"Truncate" => "Truncate",
	"Are you sure want to remove all system logs?" => "Are you sure want to remove all system logs?",
	"Are you sure want to remove selected logs?" => "Are you sure want to remove selected logs?",
	"Delete" => "Delete",
	"{User} has updated webiste's ({Website}) information" => "{User} has updated URL ({Website}) information",
	"Selected logs has been removed" => "Selected logs has been removed",

	"All suggestions has been removed" => "All suggestions has been removed",
	"Are you sure want to remove all suggestions?" => "Are you sure want to remove all suggestions?",
	"Are you sure want to remove selected suggestions?" => "Are you sure want to remove selected suggestions?",
	"Selected suggestions has been removed" => "Selected suggestions has been removed",

	"Category suggestion" => "Category suggestion",
	"{User} has removed all suggestions" => "{User} has removed all suggestions",
	"{User} has removed {Count} suggestion(-s)" => "{User} has removed {Count} suggestion(-s)",

	"Category module" => "Category module",
    "{Link} has been deleted by {User}" => "{Link} has been deleted by {User}",

	"{User} has created root ({LangID}) category" => "{User} has created root ({LangID}) category",
	"{User} has updated category {Category}" => "{User} has updated category {Category}",
	"{User} has created category {Category}" => "{User} has created category {Category}",
	"{User} has removed category {Category}" => "{User} has removed category {Category}",

    "Are you sure want to remove selected reports?" => "Are you sure want to remove selected reports?",
    "Are you sure want to remove all reports?" => "Are you sure want to remove all reports?",
    "Selected reports has been removed" => "Selected reports has been removed",
    "All reports has been removed" => "All reports has been removed",
    "{User} has removed \"broken link report\"" => "{User} has removed \"broken link report\"",
    "{User} has removed \"request for update\"" => "{User} has removed \"request for update\"",
    "Remove this report" => "Remove this report",
    "Are you sure want to remove this report?" => "Are you sure want to remove this report?",

    "Cache has been cleared" => "Cache has been cleared",
    "Sitemap has been generated" => "Sitemap has been generated",
    "Cache has been cleared by {User}" => "Cache has been cleared by {User}",
    "Sitemap has been generated by {User}" => "Sitemap has been generated by {User}",
    "Tools module" => "Tools module",

    "Total number of links in each category generated by {User}" => "Total number of links in each category generated by {User}",
    "Total number of links in each category has been generated" => "Total number of links in each category has been generated",

    "CRON module"=>"CRON module",
    "URL: {Link}. Status has been changed from Premium to Regular" => "URL: {Link}. Status has been changed from Premium to Regular",
);