<?php
return array(
	"ID" => "ID",
	"User" => "Bruger",
	"Module" => "Modul",
	"Log" => "Log",
    "System log" => "System log",
	"Created at" => "Oprettet",
	"Website module" => "hjemmeside modul",
	"All systems log has been removed" => "Alle system logs er fjernet",
	"Truncate" => "Truncate (Slet alt)",
	"Are you sure want to remove all system logs?" => "Er du siker på du vil fjernet alle system logs?",
	"Are you sure want to remove selected logs?" => "Er du sikker på at du vil fjerne valgte logs?",
	"Delete" => "Slet",
	"{User} has updated webiste's ({Website}) information" => "{User} har opdateret hjemmesiden: ({Website})´s information",
	"Selected logs has been removed" => "Valgte logs er fjernet",

	"All suggestions has been removed" => "Alle foreslag er nu fjernet",
	"Are you sure want to remove all suggestions?" => "Er du sikker på at du vil fjerne alle foreslag?",
	"Are you sure want to remove selected suggestions?" => "Er du sikker på at du vil fjerne de valgte foreslag?",
	"Selected suggestions has been removed" => "Valgte foreslag er fjernet",

	"Category suggestion" => "Kategori foreslag",
	"{User} has removed all suggestions" => "{User} har fjernet alle forslag",
	"{User} has removed {Count} suggestion(-s)" => "{User} har fjernet {Count} foreslag",

	"Category module" => "Kategori modul",
    "{Link} has been deleted by {User}" => "{Link} er slettet af brugeren {User}",

	"{User} has created root ({LangID}) category" => "{User} har oprettet rod ({LangID}) kategori",
	"{User} has updated category {Category}" => "{User} har opdateret kategori {Category}",
	"{User} has created category {Category}" => "{User} har oprettet kategori {Category}",
	"{User} has removed category {Category}" => "{User} har fjernet kategori {Category}",

    "Are you sure want to remove selected reports?" => "Er du sikker på at du vil fjerne de valgte rapporter?",
    "Are you sure want to remove all reports?" => "Er du sikker på at du vil fjerne alle rapporter?",
    "Selected reports has been removed" => "Valgte rapporter er nu fjernet",
    "All reports has been removed" => "Alle rapporter er nu fjernet",
    "{User} has removed \"broken link report\"" => "{User} har fjernet \"broken link report\"",
    "{User} has removed \"request for update\"" => "{User} har fjernet \"request for update\"",
    "Remove this report" => "Fjern denne rapport",
    "Are you sure want to remove this report?" => "Er du siker på at du vil fjerne denne rapport?",

    "Cache has been cleared" => "Cache blev tømt",
    "Sitemap has been generated" => "Sitemap er nu oprettet",
    "Cache has been cleared by {User}" => "Cache blev tømt af brugeren {User}",
    "Sitemap has been generated by {User}" => "Sitemap blev oprettet af {User}",
    "Tools module" => "Værktøjs modul",

    "Total number of links in each category generated by {User}" => "Samlet antal links i hver kategori genereret af {User}",
    "Total number of links in each category has been generated" => "Samlet antal links i hver kategori er blevet genereret",

    "CRON module"=>"CRON modul",
    "URL: {Link}. Status has been changed from Premium to Regular" => "URL: {Link}. Status er ændret fra Premium til normal",
);