<?php
return array(
	"ID" => "ID",
	"User" => "Пользователь",
	"Module" => "Модуль",
	"Log" => "Журнал",
    "System log" => "Системные логи",
	"Created at" => "Создан",
	"Website module" => "Модуль Ссылок",
	"All systems log has been removed" => "Все системные логи были удалены",
	"Truncate" => "Очистить",
	"Are you sure want to remove all system logs?" => "Вы действительно хотите удалить все системные логи?",
	"Are you sure want to remove selected logs?" => "Вы действительно хотите удалить выбранные логи?",
	"Delete" => "Удалить",
	"{User} has updated webiste's ({Website}) information" => "Пользователь {User} обновил информацию о сайте: {Website}",
	"Selected logs has been removed" => "Выбранные логи были удалены",

	"All suggestions has been removed" => "Все предложения были удалены",
	"Are you sure want to remove all suggestions?" => "Вы действительно хотите удалить все предложения?",
	"Are you sure want to remove selected suggestions?" => "Вы действительно хотите удалить выбранные предложения?",
	"Selected suggestions has been removed" => "Выбранные предложения были удалены",

	"Category suggestion" => "Предложения новых категорий",
	"{User} has removed all suggestions" => "Пользователь {User} удалил все предложения",
	"{User} has removed {Count} suggestion(-s)" => "Пользователь {User} удалил {Count} предложений",

	"Category module" => "Модуль категорий",
    "{Link} has been deleted by {User}" => "{Link} ссылка была удалена пользователем {User}",

	"{User} has created root ({LangID}) category" => "Пользователь {User} создал корневую директорию ({LangID})",
	"{User} has updated category {Category}" => "Пользователь {User} обновил категорию {Category}",
	"{User} has created category {Category}" => "Пользователь {User} создал категорию {Category}",
	"{User} has removed category {Category}" => "Пользователь {User} удалил категорию {Category}",

    "Are you sure want to remove selected reports?" => "Вы действительно хотите удалить выбранные отчеты?",
    "Are you sure want to remove all reports?" => "Вы действительно хотите удалить все отчеты?",
    "Selected reports has been removed" => "Выбранные отчеты были удалены",
    "All reports has been removed" => "Все отчеты были удалены",
    "{User} has removed \"broken link report\"" => "Пользователь {User} удалил отчет о битой ссылке",
    "{User} has removed \"request for update\"" => "Пользователь {User} удалил отчет о запросе для обновление информации о ссылке",
    "Remove this report" => "Удалить этот отчет",
    "Are you sure want to remove this report?" => "Вы действительно хотите удалить этот отчет?",

    "Cache has been cleared" => "Кеш был очистен",
    "Sitemap has been generated" => "Генерация карты сайта прошла успешно",
    "Cache has been cleared by {User}" => "Пользователь {User} очистил кеш",
    "Sitemap has been generated by {User}" => "Карта сайта была сгенерирована пользователем {User}",
    "Tools module" => "Модуль инструментов",

    "Total number of links in each category generated by {User}" => "Пользователь {User} сгенерировал количество линков в каждой категории",
    "Total number of links in each category has been generated" => "Сгенерировано количество линков в каждой категории",

    "CRON module"=>"CRON модуль",
    "URL: {Link}. Status has been changed from Premium to Regular" => "URL: {Link}. Статус был изменен с Премиум на Регулярный",
);