<?php
class ToolsController extends BackController {
    public function actionIndex() {
        $this -> title = Yii::t("admin", "Tools");
        $this -> render("//tools/index");
    }

    public function actionGenerateSitemap() {
        $args = array('yiic', 'sitemap');
        $commandPath = Yii::app() -> getBasePath() . DIRECTORY_SEPARATOR . 'commands';

        // Create new console command runner
        $runner = new CConsoleCommandRunner();

        // Adding commands
        $runner -> addCommands($commandPath);

        // If something goes wrong return error
        if($error = $runner -> run ($args)) {
            Yii::app()->user->setFlash("danger", Yii::t("system_log", "Sitemap error code $error"));
        } else {
            $log = new SystemLog();
            $log -> module = "Tools module";
            $log -> log = "Sitemap has been generated by {User}";
            $log -> save();
            Yii::app()->user->setFlash("success", Yii::t("system_log", "Sitemap has been generated"));
        }
        $this->redirect(array("admin/tools/index"));
    }

    public function actionGenerateWebsiteCount() {
        $args = array('yiic', 'urlcalculator');
        $commandPath = Yii::app() -> getBasePath() . DIRECTORY_SEPARATOR . 'commands';

        // Create new console command runner
        $runner = new CConsoleCommandRunner();

        // Adding commands
        $runner -> addCommands($commandPath);

        // If something goes wrong return error
        if($error = $runner -> run ($args)) {
            Yii::app()->user->setFlash("danger", Yii::t("system_log", "Website calculator error code $error"));
        } else {
            $log = new SystemLog();
            $log -> module = "Tools module";
            $log -> log = "Total number of links in each category generated by {User}";
            $log -> save();
            Yii::app()->user->setFlash("success", Yii::t("system_log", "Total number of links in each category has been generated"));
        }
        $this->redirect(array("admin/tools/index"));
    }

    public function actionClearCache() {
        $log = new SystemLog();
        $log -> module = "Tools module";
        $log -> log = "Cache has been cleared by {User}";
        $log -> save();
        Yii::app()->cache->flush();
        yii::app()->user->setFlash("success", Yii::t("system_log", "Cache has been cleared"));
        $this->redirect(array("admin/tools/index"));
    }
}